[package]
name = "jit"
version = "0.1.0"
authors = ["Ben Lipton <ben.lipton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.14"
structopt = "0.3.13"
anyhow = "1.0.28"
maplit = "1.0.2"
rust-crypto = "0.2.36"
rand = "0.7.3"
